### ISSUE TITLE
NetCore project doesn't reference when used in sample app

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-csharp#15]
not sure why but the namespace `ZulipNetCore` doesn't include any classes. They all seem to be `inaccessible due to their protection level`. However all classes and constructors are public.

Therefore until this is fixed I need the other Project `ZulipClient` to build the class library and test it in the `SampleApp`

**Comment by priyank-p** [comment]
I know why this is now working sending a fix.

**Comment by penCsharpener** [comment]
thanks @cPhost 
even though your PR didn't work you pointed me in the right direction. fixed with [e477b26](https://github.com/zulip/zulip-csharp/commit/e477b2643af87b8428bcd5e9414f8b23221953d3)
