### ISSUE TITLE
Add error handling

### ISSUE THREAD

**Issue by priyank-p** [zulip/zulip-csharp#27]
Add error handling when an error occurs when a response is missing something like invalid credentials. 

Right now if we send wrong credential it will send a error json that we can ourself parse on our end. So users using it do not have to implement one.

**Comment by cPhost** [comment]
@zulipbot label "enhancement"

**Comment by penCsharpener** [comment]
just to narrow the scrope of this issue a little bit
* [ ] invalid credentials
* [x] improvements for `ZulipRCAuth.cs`
* [ ] think of errors that can occur in the currently available endpoints
* [ ] writing tests that simulate those errors 
* [x] create error handling that catch them in a user friendly way
* whatever else is best practice

**Comment by penCsharpener** [comment]
So each implemented endpoint so far now has a custom exception class that can take an object of type `ResponseBase` which which all other response classes are derived. 

A response class usually consists of three properties, of which two are always the same: `msg` and `result`. `result` returns whether the api call was successful. If it returns 'error' then `msg` will have some extra information from the Zulip server. 

The third property is the array of items returned if the call was successful and is parse further into .NET objects.
